### PR TITLE
Add support for no global access and CORS responses

### PR DESCRIPTION
**Pull request by ChristopherEdwards**
Add additional conditionals where global access occurs to disable
access if the NOGBL flag is set

Add basic support for CORS

Add support for basic authentication passed during web server startup

### CODE REVIEW

**Comment by ChristopherEdwards** [comment]
These are my test notes for creating unit tests:

 ; NOGBL tests:
 ; %webapi - Where is our home?
 ; %webhome - kill of ^TMP("HTTPERR",$J),HTTPERR,RESULT
 ;            return "NO INDEX FOUND!"
 ; %webreq - stop the listener on $E(^%webhttp(0,"listener"),1,4)=stop
 ;         - passing of USERPASS
 ;         - HTTPLOG=0
 ;         - SETERROR^%webutils(501,"Log ID:")
 ;         - RSPERROR^%webutils
 ; %webrsp - ^%web(17.6001) matching
 ;         - RSPERROR is skipped (nothing in ^TMP("HTTPERR",$J))
 
 ; CORS tests
 ; %webrsp - method=OPTIONS retruns OPTIONS,POST
 ;
 ; I $G(HTTPREQ("method"))="OPTIONS" D W("Access-Control-Allow-Methods: OPTIONS, POST"_$C(13,10))
 ; I $G(HTTPREQ("method"))="OPTIONS" D W("Access-Control-Allow-Headers: Content-Type"_$C(13,10))
 ; I $G(HTTPREQ("method"))="OPTIONS" D W("Access-Control-Max-Age: 86400"_$C(13,10))
 ; D W("Access-Control-Allow-Origin: *"_$C(13,10))
 
 ; USERPASS tests
 ; %webrsp  - make sure passed username works and errors occur

**Comment by shabiel** [comment]
That's good.

**Comment by ChristopherEdwards** [comment]
@shabiel I think I've added tests that should cover everything. Also added a `Dockerfile` that will run the tests too (which is how I tested my changes as I went along).

**Comment by shabiel** [comment]
Thank you!

**Pull request merged**
